import React, { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";

import { JianghuPageAtmosphere, JianghuPaperPanel, jianghuColors } from "@/components/jianghu-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useGame, type Difficulty, type TaskType, difficultyLabel, typeLabel } from "@/lib/game-store";

const typeSeals: Record<TaskType, string> = { inner: "氣", body: "力", wisdom: "悟", reputation: "名" };
const typeColors: Record<TaskType, string> = { inner: "#2E8B91", body: "#C98635", wisdom: "#7661B5", reputation: "#C94D42" };

export default function TaskScreen() {
  const game = useGame();
  const { id } = useLocalSearchParams<{ id?: string }>();
  const existing = game.tasks.find((task) => task.id === id);
  const [title, setTitle] = useState(existing?.title ?? "");
  const [type, setType] = useState<TaskType>(existing?.type ?? "inner");
  const [difficulty, setDifficulty] = useState<Difficulty>(existing?.difficulty ?? "normal");
  const save = () => { if (!title.trim()) return; if (existing) game.updateTask(existing.id, { title: title.trim(), type, difficulty }); else game.addTask({ title: title.trim(), description: "新的修煉目標", type, difficulty, due: "今天 21:00" }); router.back(); };

  return <ScreenContainer containerClassName="bg-[#F4F1E7]" className="px-4"><View style={styles.page}><JianghuPageAtmosphere /><ScrollView style={styles.scroll} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.head}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><Text style={styles.backText}>‹ 返回</Text></Pressable><Text style={styles.heading}>{existing ? "修訂江湖令" : "接取江湖令"}</Text><View style={styles.headSpacer} /></View>
    <View style={styles.scrollIntro}><View style={styles.introSeal}><Text style={styles.introSealText}>令</Text></View><View style={styles.introCopy}><Text style={styles.introKicker}>{existing ? "重整修煉方向" : "門派任務簿"}</Text><Text style={styles.introText}>{existing ? "調整這份江湖令，讓今日功課更貼近你的節奏。" : "寫下現實目標，交由少俠化為今日試煉。"}</Text></View></View>
    <JianghuPaperPanel style={styles.form}><Text style={styles.fieldLabel}>修煉題目</Text><TextInput value={title} onChangeText={setTitle} placeholder="例如：完成專案簡報" placeholderTextColor="#8C948B" style={styles.input} returnKeyType="done" onSubmitEditing={save} />
      <View style={styles.rule} /><Text style={styles.fieldLabel}>選擇武學令牌</Text><Text style={styles.fieldHint}>任務的修煉方向，會回饋對應四象能力。</Text><View style={styles.typeGrid}>{(["inner", "body", "wisdom", "reputation"] as TaskType[]).map((entry) => <Pressable key={entry} onPress={() => setType(entry)} style={({ pressed }) => [styles.typeChoice, type === entry && { borderColor: typeColors[entry], backgroundColor: `${typeColors[entry]}18` }, pressed && styles.pressed]}><View style={[styles.typeSeal, { borderColor: typeColors[entry], backgroundColor: type === entry ? typeColors[entry] : "#F8F4E9" }]}><Text style={[styles.typeSealText, { color: type === entry ? "#FFFFFF" : typeColors[entry] }]}>{typeSeals[entry]}</Text></View><Text style={[styles.typeText, type === entry && { color: typeColors[entry] }]}>{typeLabel[entry]}</Text></Pressable>)}</View>
      <View style={styles.rule} /><Text style={styles.fieldLabel}>蓋下難度印章</Text><Text style={styles.fieldHint}>難度影響本次完成後獲得的修為與江湖幣。</Text><View style={styles.difficultyRow}>{(["normal", "hard", "epic"] as Difficulty[]).map((entry) => <Pressable key={entry} onPress={() => setDifficulty(entry)} style={({ pressed }) => [styles.difficultyChoice, difficulty === entry && styles.difficultyActive, pressed && styles.pressed]}><Text style={[styles.difficultyText, difficulty === entry && styles.difficultyTextActive]}>{difficultyLabel[entry]}</Text></Pressable>)}</View>
    </JianghuPaperPanel>
    <View style={styles.footerNote}><Text style={styles.footerNoteMark}>守</Text><Text style={styles.footerNoteText}>所有修煉紀錄都會保存於此裝置的江湖手札中。</Text></View>
    <Pressable onPress={save} style={({ pressed }) => [styles.save, pressed && styles.pressed]}><View style={styles.saveSeal}><Text style={styles.saveSealText}>令</Text></View><Text style={styles.saveText}>{existing ? "更新修煉之約" : "立下修煉之約"}</Text></Pressable>
  </ScrollView></View></ScreenContainer>;
}

const styles = StyleSheet.create({
  page: { flex: 1, position: "relative" }, scroll: { zIndex: 1 }, content: { paddingTop: 10, paddingBottom: 34 },
  head: { minHeight: 52, flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }, back: { width: 68, paddingVertical: 9 }, backText: { color: jianghuColors.jade, fontSize: 13, lineHeight: 17, fontWeight: "900" }, heading: { color: jianghuColors.ink, fontSize: 19, lineHeight: 25, fontWeight: "900" }, headSpacer: { width: 68 },
  scrollIntro: { minHeight: 87, borderRadius: 23, padding: 15, flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: "rgba(49,95,120,0.94)", borderWidth: 1, borderColor: "#B99459", shadowColor: "#315F78", shadowOpacity: 0.16, shadowRadius: 9, elevation: 3 }, introSeal: { width: 44, height: 44, borderRadius: 14, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#FFE7A0", backgroundColor: "rgba(255,244,211,0.10)" }, introSealText: { color: "#FFE7A0", fontSize: 22, lineHeight: 28, fontWeight: "900" }, introCopy: { flex: 1 }, introKicker: { color: "#D2F0E6", fontSize: 10, lineHeight: 14, letterSpacing: 1, fontWeight: "900" }, introText: { color: "#FFF9E8", fontSize: 12, lineHeight: 18, fontWeight: "700", marginTop: 3 },
  form: { padding: 18, marginTop: 16 }, fieldLabel: { color: jianghuColors.ink, fontSize: 15, lineHeight: 20, fontWeight: "900" }, fieldHint: { color: "#788981", fontSize: 11, lineHeight: 16, marginTop: 4 }, input: { borderWidth: 1, borderColor: "#D6CFBF", borderRadius: 15, paddingHorizontal: 13, paddingVertical: 13, backgroundColor: "#F8F4E9", color: jianghuColors.ink, fontSize: 15, lineHeight: 20, marginTop: 10 }, rule: { height: 1, backgroundColor: "#E4DDCE", marginVertical: 20 }, typeGrid: { flexDirection: "row", flexWrap: "wrap", gap: 9, marginTop: 12 }, typeChoice: { width: "47.8%", flexDirection: "row", alignItems: "center", gap: 8, borderRadius: 15, padding: 10, borderWidth: 1, borderColor: "#D8D1C1", backgroundColor: "#FFFDF6" }, typeSeal: { width: 28, height: 28, borderRadius: 10, borderWidth: 1, alignItems: "center", justifyContent: "center" }, typeSealText: { fontSize: 13, lineHeight: 17, fontWeight: "900" }, typeText: { color: "#5C746E", fontSize: 12, lineHeight: 16, fontWeight: "900" }, difficultyRow: { flexDirection: "row", gap: 8, marginTop: 12 }, difficultyChoice: { flex: 1, alignItems: "center", borderRadius: 13, paddingVertical: 10, borderWidth: 1, borderColor: "#D8D1C1", backgroundColor: "#FFFDF6" }, difficultyActive: { borderColor: "#B16C22", backgroundColor: "#C98536" }, difficultyText: { color: "#657C75", fontSize: 11, lineHeight: 15, fontWeight: "800" }, difficultyTextActive: { color: "#FFFFFF", fontWeight: "900" },
  footerNote: { flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 8, marginTop: 14 }, footerNoteMark: { width: 20, height: 20, borderRadius: 10, color: jianghuColors.jade, backgroundColor: "#E5EEE5", fontSize: 10, lineHeight: 20, fontWeight: "900", textAlign: "center" }, footerNoteText: { flex: 1, color: "#788981", fontSize: 10, lineHeight: 15 }, save: { minHeight: 54, borderRadius: 18, marginTop: 20, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: jianghuColors.cinnabar, borderWidth: 1, borderColor: "#A83B32", shadowColor: jianghuColors.cinnabar, shadowOpacity: 0.22, shadowRadius: 8, elevation: 4 }, saveSeal: { width: 24, height: 24, borderRadius: 8, borderWidth: 1, borderColor: "rgba(255,231,160,0.70)", alignItems: "center", justifyContent: "center" }, saveSealText: { color: "#FFE7A0", fontSize: 12, lineHeight: 16, fontWeight: "900" }, saveText: { color: "#FFFFFF", fontSize: 14, lineHeight: 18, fontWeight: "900" }, pressed: { opacity: 0.82, transform: [{ scale: 0.98 }] },
});
