import React, { useState } from "react";
import { Alert, Image, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { CharacterAvatar } from "@/components/character-avatar";
import { ScreenContainer } from "@/components/screen-container";
import { JianghuPageAtmosphere, JianghuPaperPanel } from "@/components/jianghu-ui";
import { itemById, levelTitle, useGame } from "@/lib/game-store";
import { inventoryBanner } from "@/lib/custom-assets";
import { avatarItemById, avatarRarityColor, avatarRarityLabel, avatarSlotLabel, type AvatarItem } from "@/lib/avatar-system";

export default function InventoryScreen() {
  const game = useGame();
  const [previewItem, setPreviewItem] = useState<AvatarItem | null>(null);
  const consumables = game.inventory.filter((entry) => itemById(entry.id)?.type === "consumable" && entry.quantity > 0);
  const ownedLooks = game.ownedItems.map((id) => itemById(id)).filter(Boolean);
  const ownedAvatarItems = game.userItems.filter((entry) => entry.owned).map((entry) => avatarItemById(entry.item_id)).filter((item): item is AvatarItem => Boolean(item));
  const equipped = avatarItemById(game.avatarEquipment.outfit) ?? (game.equippedItem ? itemById(game.equippedItem) : undefined);

  return <ScreenContainer containerClassName="bg-[#F4F1E7]" className="px-5"><View style={inventoryPageStyles.page}><JianghuPageAtmosphere /><ScrollView style={inventoryPageStyles.scroll} showsVerticalScrollIndicator={false} contentContainerStyle={styles.scrollContent}>
    <View style={styles.head}><View><Text style={styles.kicker}>隨身行囊</Text><Text style={styles.heading}>背包</Text></View><Text style={styles.headHint}>收納今日收穫</Text></View>
    <View style={[styles.banner, inventoryBannerLayers.banner]}><Image source={inventoryBanner} style={inventoryBannerLayers.background} resizeMode="cover" /><View style={[styles.sceneShade, inventoryBannerLayers.textShade]} /><CharacterAvatar equipment={game.avatarEquipment} height={205} style={styles.bannerAvatar} accessibilityLabel="行囊場景中的目前角色外觀" /><View style={[styles.bannerCopy, inventoryBannerLayers.copy]}><Text style={styles.bannerKicker}>{game.sect} · {levelTitle(game.level)}</Text><Text style={styles.bannerTitle}>江湖行囊</Text><Text style={styles.bannerBody}>{equipped ? `已配備「${equipped.name}」` : "收納道具、裝備與每一段修煉收穫。"}</Text></View><View style={[styles.bannerBelt, inventoryBannerLayers.belt]}><View style={styles.bannerStat}><Text style={styles.bannerStatValue}>{consumables.length}</Text><Text style={styles.bannerStatLabel}>可用道具</Text></View><View style={styles.bannerDivider} /><View style={styles.bannerStat}><Text style={styles.bannerStatValue}>{ownedAvatarItems.length}</Text><Text style={styles.bannerStatLabel}>已解鎖外觀</Text></View></View></View>

    <View style={styles.sectionRow}><Text style={styles.section}>消耗品</Text><Text style={styles.meta}>{consumables.length ? `${consumables.length} 種可用` : "暫無道具"}</Text></View>
    {consumables.length === 0 ? <View style={styles.emptyPanel}><Text style={styles.emptyIcon}>囊</Text><Text style={styles.empty}>目前沒有可使用的道具，去商鋪看看吧。</Text></View> : <View style={styles.listPanel}>{consumables.map((entry) => { const item = itemById(entry.id); if (!item) return null; const active = entry.activeUntil && new Date(entry.activeUntil).getTime() > Date.now(); return <View key={entry.id} style={styles.itemRow}><View style={styles.itemIcon}>{item.imageUrl ? <Image source={{ uri: item.imageUrl }} style={styles.itemImage} resizeMode="contain" /> : <Text style={styles.itemIconText}>{item.icon}</Text>}</View><View style={styles.itemCopy}><Text style={styles.itemName}>{item.name}</Text><Text style={styles.itemDescription}>{item.description}</Text><Text style={styles.quantity}>持有 {entry.quantity}{active ? " · 效果中" : ""}</Text></View><Pressable disabled={Boolean(active)} onPress={() => { if (!game.useItem(entry.id)) Alert.alert("無法使用", "請稍後再試。"); }} style={({ pressed }) => [styles.useButton, active && styles.usedButton, pressed && !active && styles.pressed]}><Text style={active ? styles.usedText : styles.useText}>{active ? "效果中" : "使用"}</Text></Pressable></View>; })}</View>}

    <View style={styles.sectionRow}><Text style={styles.section}>已解鎖外觀</Text><Text style={styles.meta}>{ownedLooks.length} 件收藏</Text></View>
    {ownedLooks.length === 0 ? <View style={styles.emptyPanel}><Text style={styles.emptyIcon}>衣</Text><Text style={styles.empty}>尚未解鎖外觀，前往商鋪收藏你的江湖裝備。</Text></View> : <View style={styles.listPanel}>{ownedLooks.map((item) => item ? <View key={item.id} style={styles.lookRow}><View style={styles.lookIcon}>{item.imageUrl ? <Image source={{ uri: item.imageUrl }} style={styles.lookImage} resizeMode="contain" /> : <Text style={styles.lookIconText}>{item.icon}</Text>}</View><View style={styles.itemCopy}><Text style={styles.itemName}>{item.name}</Text><Text style={styles.itemDescription}>{item.type === "weapon" ? "武器" : "服飾"} · {game.equippedItem === item.id ? "目前裝備" : "已收藏"}</Text></View><View style={game.equippedItem === item.id ? styles.equippedPill : styles.collectedPill}><Text style={game.equippedItem === item.id ? styles.equippedText : styles.collectedText}>{game.equippedItem === item.id ? "已裝備" : "收藏"}</Text></View></View> : null)}</View>}
    <View style={styles.sectionRow}><Text style={styles.section}>角色外觀</Text><Text style={styles.meta}>{ownedAvatarItems.length} 件收藏</Text></View>
    {ownedAvatarItems.length === 0 ? <View style={styles.emptyPanel}><Text style={styles.emptyIcon}>飾</Text><Text style={styles.empty}>完成成就或前往商鋪，即可獲得可試穿的角色外觀。</Text></View> : <View style={styles.listPanel}>{ownedAvatarItems.map((item) => { const equipped = game.avatarEquipment[item.type] === item.id; return <Pressable key={item.id} onPress={() => setPreviewItem(item)} style={({ pressed }) => [styles.lookRow, pressed && styles.pressed]}><View style={[styles.lookIcon, { borderColor: avatarRarityColor[item.rarity], borderWidth: 1 }]}><Text style={[styles.lookIconText, { color: avatarRarityColor[item.rarity] }]}>{avatarSlotLabel[item.type].slice(0, 1)}</Text></View><View style={styles.itemCopy}><Text style={styles.itemName}>{item.name}</Text><Text style={styles.itemDescription}>{avatarSlotLabel[item.type]} · {avatarRarityLabel[item.rarity]} · {equipped ? "目前裝備" : "點擊試穿"}</Text></View><View style={equipped ? styles.equippedPill : styles.collectedPill}><Text style={equipped ? styles.equippedText : styles.collectedText}>{equipped ? "已裝備" : "試穿"}</Text></View></Pressable>; })}</View>}
    <Text style={styles.section}>行囊提示</Text><View style={styles.note}><Text style={styles.noteTitle}>帶著收穫繼續闖蕩</Text><Text style={styles.noteBody}>消耗品會在本地保存；經驗加成只在啟用後的期限內生效。外觀可於商鋪購買並裝備。</Text></View>
  </ScrollView><InventoryTryOnModal item={previewItem} onClose={() => setPreviewItem(null)} /></View></ScreenContainer>;
}

function InventoryTryOnModal({ item, onClose }: { item: AvatarItem | null; onClose: () => void }) {
  const game = useGame();
  if (!item) return null;
  const equipped = game.avatarEquipment[item.type] === item.id;
  const previewEquipment = { ...game.avatarEquipment, [item.type]: item.id };
  return <Modal visible transparent animationType="fade" onRequestClose={onClose}><View style={styles.tryOnBackdrop}><JianghuPaperPanel style={styles.tryOnCard}><Pressable onPress={onClose} style={styles.tryOnClose}><Text style={styles.tryOnCloseText}>×</Text></Pressable><Text style={styles.tryOnKicker}>{avatarSlotLabel[item.type]} · {avatarRarityLabel[item.rarity]}</Text><Text style={styles.tryOnTitle}>{item.name}</Text><View style={styles.tryOnFrame}><CharacterAvatar equipment={previewEquipment} height={238} accessibilityLabel={`試穿 ${item.name} 的角色模型`} /></View><Text style={[styles.tryOnDescription, { color: avatarRarityColor[item.rarity] }]}>{item.description}</Text><View style={styles.tryOnActions}><Pressable onPress={() => { game.unequipAvatarSlot(item.type); onClose(); }} style={({ pressed }) => [styles.unequipButton, pressed && styles.pressed]}><Text style={styles.unequipButtonText}>卸下</Text></Pressable><Pressable onPress={() => { game.equipAvatarItem(item.id); onClose(); }} style={({ pressed }) => [styles.equipAvatarButton, equipped && styles.equipAvatarButtonActive, pressed && styles.pressed]}><Text style={styles.equipAvatarButtonText}>{equipped ? "已裝備" : "裝備此物"}</Text></Pressable></View></JianghuPaperPanel></View></Modal>;
}

const inventoryPageStyles = StyleSheet.create({
  page: { flex: 1, position: "relative" },
  scroll: { zIndex: 1 },
});

const inventoryBannerLayers = StyleSheet.create({
  background: { ...StyleSheet.absoluteFillObject, width: "100%", height: "100%" },
  banner: { minHeight: 218 },
  textShade: { width: "70%", backgroundColor: "rgba(11,39,48,0.50)" },
  copy: { zIndex: 3 },
  belt: { zIndex: 4 },
});

const styles = StyleSheet.create({
  scrollContent: { paddingBottom: 42 }, head: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end", paddingTop: 12, paddingBottom: 16 }, kicker: { color: "#2E8B91", fontSize: 11, letterSpacing: 1.2, fontWeight: "900" }, heading: { color: "#18343C", fontSize: 27, fontWeight: "900", marginTop: 3 }, headHint: { color: "#7C9798", fontSize: 11, fontWeight: "700", marginBottom: 4 },
  banner: { minHeight: 194, borderRadius: 24, overflow: "hidden", padding: 17, justifyContent: "center", backgroundColor: "#2E8B91" }, bannerImage: { borderRadius: 24 }, sceneShade: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(19,59,66,0.38)" }, bannerCharacter: { position: "absolute", right: -10, bottom: 35, width: 165, height: 174 }, bannerAvatar: { position: "absolute", right: -9, bottom: 23, zIndex: 2 }, bannerCopy: { zIndex: 3, width: "66%", paddingBottom: 40 }, bannerKicker: { color: "#C9F3E7", fontSize: 10, letterSpacing: 0.8, fontWeight: "900" }, bannerTitle: { color: "#FFFFFF", fontSize: 23, fontWeight: "900", marginTop: 6 }, bannerBody: { color: "#E0F5ED", fontSize: 11, lineHeight: 17, marginTop: 7 }, bannerBelt: { position: "absolute", left: 12, right: 12, bottom: 12, height: 48, borderRadius: 15, paddingHorizontal: 13, backgroundColor: "rgba(24,62,71,0.78)", borderWidth: 1, borderColor: "rgba(255,225,138,0.34)", flexDirection: "row", alignItems: "center", zIndex: 4 }, bannerStat: { flex: 1, alignItems: "center" }, bannerStatValue: { color: "#FFF0C8", fontSize: 15, fontWeight: "900" }, bannerStatLabel: { color: "#C9F3E7", fontSize: 9, fontWeight: "800", marginTop: 1 }, bannerDivider: { width: 1, height: 22, backgroundColor: "rgba(255,255,255,0.22)" },
  sectionRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "baseline", marginTop: 24, marginBottom: 9 }, section: { color: "#18343C", fontWeight: "900", fontSize: 19 }, meta: { color: "#7C9798", fontSize: 11, fontWeight: "700" }, listPanel: { overflow: "hidden", borderRadius: 20, backgroundColor: "rgba(255,255,255,0.72)", borderWidth: 1, borderColor: "#DCEEE9" }, itemRow: { minHeight: 78, flexDirection: "row", alignItems: "center", gap: 10, padding: 12, borderBottomWidth: 1, borderBottomColor: "#E5F0ED" }, itemIcon: { width: 48, height: 48, borderRadius: 15, backgroundColor: "#FFF3D5", alignItems: "center", justifyContent: "center" }, itemImage: { width: 43, height: 43 }, itemIconText: { color: "#D99632", fontSize: 19, fontWeight: "900" }, itemCopy: { flex: 1 }, itemName: { color: "#18343C", fontSize: 13, fontWeight: "900" }, itemDescription: { color: "#7C9798", fontSize: 10, lineHeight: 15, marginTop: 3 }, quantity: { color: "#D99632", fontSize: 10, fontWeight: "900", marginTop: 3 }, useButton: { borderRadius: 12, backgroundColor: "#E86D67", paddingHorizontal: 12, paddingVertical: 9 }, useText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" }, usedButton: { backgroundColor: "#E7F2EF" }, usedText: { color: "#7C9798", fontSize: 11, fontWeight: "900" },
  lookRow: { minHeight: 66, flexDirection: "row", alignItems: "center", gap: 10, padding: 12, borderBottomWidth: 1, borderBottomColor: "#E5F0ED" }, lookIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#E8F5F1", alignItems: "center", justifyContent: "center" }, lookImage: { width: 37, height: 37 }, lookIconText: { color: "#2E8B91", fontWeight: "900", fontSize: 16 }, equippedPill: { backgroundColor: "#FFF0C8", borderRadius: 11, paddingHorizontal: 9, paddingVertical: 6 }, collectedPill: { backgroundColor: "#E7F2EF", borderRadius: 11, paddingHorizontal: 9, paddingVertical: 6 }, equippedText: { color: "#A66B16", fontSize: 10, fontWeight: "900" }, collectedText: { color: "#6D8587", fontSize: 10, fontWeight: "900" },
  emptyPanel: { minHeight: 76, borderRadius: 18, backgroundColor: "rgba(255,255,255,0.66)", borderWidth: 1, borderColor: "#DCEEE9", padding: 14, flexDirection: "row", alignItems: "center", gap: 10 }, emptyIcon: { width: 34, height: 34, borderRadius: 12, backgroundColor: "#E8F5F1", color: "#2E8B91", textAlign: "center", paddingTop: 8, fontWeight: "900" }, empty: { flex: 1, color: "#7C9798", fontSize: 12, lineHeight: 18 }, note: { borderRadius: 20, padding: 15, backgroundColor: "#FFF4D6", borderWidth: 1, borderColor: "#F0DEB0" }, noteTitle: { color: "#8A6224", fontSize: 12, fontWeight: "900" }, noteBody: { color: "#806E50", fontSize: 11, lineHeight: 17, marginTop: 5 }, tryOnBackdrop: { flex: 1, backgroundColor: "rgba(20,52,51,0.58)", justifyContent: "center", alignItems: "center", padding: 20 }, tryOnCard: { width: "100%", padding: 19, alignItems: "center" }, tryOnClose: { position: "absolute", right: 12, top: 12, width: 30, height: 30, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: "#E8EFE8", zIndex: 2 }, tryOnCloseText: { color: "#315F78", fontSize: 21, lineHeight: 25, fontWeight: "900" }, tryOnKicker: { color: "#A66B2E", fontSize: 10, lineHeight: 14, fontWeight: "900", letterSpacing: 0.8 }, tryOnTitle: { color: "#18343C", fontSize: 20, lineHeight: 26, fontWeight: "900", marginTop: 3 }, tryOnFrame: { width: "100%", height: 225, borderRadius: 18, alignItems: "center", justifyContent: "center", marginTop: 12, overflow: "hidden", backgroundColor: "#DDEDE6", borderWidth: 1, borderColor: "#BED8CC" }, tryOnDescription: { fontSize: 11, lineHeight: 16, fontWeight: "800", marginTop: 11, textAlign: "center" }, tryOnActions: { width: "100%", flexDirection: "row", gap: 9, marginTop: 14 }, unequipButton: { flex: 0.72, minHeight: 46, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#E9EFEA", borderWidth: 1, borderColor: "#CAD8CE" }, unequipButtonText: { color: "#51726B", fontSize: 12, lineHeight: 16, fontWeight: "900" }, equipAvatarButton: { flex: 1.28, minHeight: 46, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#C94D42", borderWidth: 1, borderColor: "#A63830" }, equipAvatarButtonActive: { backgroundColor: "#315F78", borderColor: "#204C60" }, equipAvatarButtonText: { color: "#FFFFFF", fontSize: 12, lineHeight: 16, fontWeight: "900" }, pressed: { opacity: 0.8, transform: [{ scale: 0.98 }] },
});
