import React, { useMemo, useState } from "react";
import { Alert, Image, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { CharacterAvatar } from "@/components/character-avatar";
import { JianghuPageAtmosphere, JianghuPaperPanel, JianghuSceneBanner, jianghuColors } from "@/components/jianghu-ui";
import { ScreenContainer } from "@/components/screen-container";
import { marketBanner } from "@/lib/custom-assets";
import { itemCatalog, useGame, type ItemType, type Rarity } from "@/lib/game-store";
import { avatarItems, avatarRarityColor, avatarRarityLabel, avatarSlotLabel, type AvatarItem } from "@/lib/avatar-system";

const rarityLabel: Record<Rarity, string> = { common: "常見", rare: "稀有", epic: "史詩", legendary: "傳說" };
const rarityColor: Record<Rarity, string> = { common: "#71817B", rare: "#3B7FA3", epic: "#7A5A9A", legendary: "#C5892E" };
const typeLabel: Record<ItemType, string> = { avatar: "頭像", frame: "相框", weapon: "武器", clothing: "服飾", consumable: "道具" };

export default function ShopScreen() {
  const game = useGame();
  const [tab, setTab] = useState<"全部" | "外觀" | "道具">("全部");
  const [previewItem, setPreviewItem] = useState<AvatarItem | null>(null);
  const list = useMemo(() => itemCatalog.filter((item) => tab === "全部" || (tab === "道具" ? item.type === "consumable" : item.type !== "consumable")), [tab]);
  const avatarList = useMemo(() => avatarItems.filter((item) => tab !== "道具"), [tab]);

  return <ScreenContainer containerClassName="bg-[#F4F1E7]" className="px-4"><View style={styles.page}><JianghuPageAtmosphere /><ScrollView style={styles.scroll} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <JianghuSceneBanner source={marketBanner} kicker="門派珍寶閣 · 今日開市" title="江湖商鋪" detail="以完成試煉換取行囊中的珍稀收穫。"><View style={styles.balance}><Text style={styles.balanceLabel}>江湖幣</Text><Text style={styles.balanceValue}>◈ {game.coin}</Text></View></JianghuSceneBanner>
    <View style={styles.sectionHead}><View><Text style={styles.kicker}>市集攤位</Text><Text style={styles.heading}>挑選你的江湖裝備</Text></View><Text style={styles.hint}>{list.length} 件珍寶</Text></View>
    <JianghuPaperPanel style={styles.tabs}>{(["全部", "外觀", "道具"] as const).map((entry) => <Pressable key={entry} onPress={() => setTab(entry)} style={({ pressed }) => [styles.tab, tab === entry && styles.tabActive, pressed && styles.pressed]}><Text style={[styles.tabText, tab === entry && styles.tabTextActive]}>{entry}</Text></Pressable>)}</JianghuPaperPanel>
    {tab !== "外觀" ? <View style={styles.grid}>{list.map((item) => {
      const quantity = game.inventory.find((entry) => entry.id === item.id)?.quantity ?? 0;
      const owned = item.type === "consumable" ? quantity > 0 : game.ownedItems.includes(item.id);
      const locked = game.level < item.minLevel;
      const equipped = game.equippedItem === item.id;
      const buy = () => { if (!game.buyItem(item.id)) Alert.alert(locked ? "尚未到達境界" : "江湖幣不足", locked ? `第 ${item.minLevel} 境後才能兌換。` : "完成更多修煉，再回來看看吧。"); };
      return <JianghuPaperPanel key={item.id} style={[styles.product, { borderColor: `${rarityColor[item.rarity]}66` }]}><View style={styles.productTop}><View style={[styles.rarityMedallion, { borderColor: rarityColor[item.rarity] }]}>{item.imageUrl ? <Image source={{ uri: item.imageUrl }} style={styles.itemImage} resizeMode="contain" /> : <Text style={[styles.itemGlyph, { color: rarityColor[item.rarity] }]}>{item.icon}</Text>}</View><Text style={[styles.rarity, { color: rarityColor[item.rarity] }]}>{rarityLabel[item.rarity]}</Text></View><Text numberOfLines={1} style={styles.productName}>{item.name}</Text><Text numberOfLines={2} style={styles.productDesc}>{item.description}</Text><View style={styles.productMeta}><Text style={styles.productType}>{typeLabel[item.type]}</Text><Text style={styles.levelRule}>Lv.{item.minLevel}</Text></View><View style={styles.priceRow}><Text style={styles.price}>◈ {item.price}</Text><Pressable disabled={owned || locked} onPress={buy} style={({ pressed }) => [styles.buyButton, (owned || locked) && styles.buyDisabled, pressed && !owned && !locked && styles.pressed]}><Text style={(owned || locked) ? styles.buyDisabledText : styles.buyText}>{locked ? "未解鎖" : owned ? (item.type === "consumable" ? `持有 ${quantity}` : "已擁有") : "兌換"}</Text></Pressable></View>{owned && item.type !== "consumable" ? <Pressable onPress={() => game.equipItem(item.id)} style={({ pressed }) => [styles.equipButton, equipped && styles.equipActive, pressed && styles.pressed]}><Text style={[styles.equipText, equipped && styles.equipTextActive]}>{equipped ? "已裝備" : "裝備"}</Text></Pressable> : <Text style={styles.productFoot}>{item.type === "consumable" && owned ? "可至背包使用" : "完成試煉可獲江湖幣"}</Text>}</JianghuPaperPanel>;
    })}</View> : null}
    {tab !== "道具" ? <><View style={styles.avatarSectionHead}><Text style={styles.avatarSectionTitle}>少俠外觀鋪</Text><Text style={styles.avatarSectionHint}>購得後可立即試穿</Text></View><View style={styles.grid}>{avatarList.map((item) => { const owned = game.userItems.some((entry) => entry.item_id === item.id && entry.owned); const equipped = game.avatarEquipment[item.type] === item.id; const buy = () => { if (!game.buyAvatarItem(item.id)) Alert.alert("江湖幣不足", "完成更多修煉，再回來換取這件外觀吧。 "); }; return <JianghuPaperPanel key={item.id} style={[styles.product, { borderColor: `${avatarRarityColor[item.rarity]}66` }]}><View style={styles.productTop}><View style={[styles.rarityMedallion, { borderColor: avatarRarityColor[item.rarity] }]}><Text style={[styles.itemGlyph, { color: avatarRarityColor[item.rarity] }]}>{avatarSlotLabel[item.type].slice(0, 1)}</Text></View><Text style={[styles.rarity, { color: avatarRarityColor[item.rarity] }]}>{avatarRarityLabel[item.rarity]}</Text></View><Text numberOfLines={1} style={styles.productName}>{item.name}</Text><Text numberOfLines={2} style={styles.productDesc}>{item.description}</Text><View style={styles.productMeta}><Text style={styles.productType}>{avatarSlotLabel[item.type]}</Text><Text style={styles.levelRule}>{item.unlock_condition}</Text></View><View style={styles.priceRow}><Text style={styles.price}>◈ {item.price_coin}</Text><Pressable onPress={owned ? () => setPreviewItem(item) : buy} style={({ pressed }) => [styles.buyButton, owned && styles.buyDisabled, pressed && styles.pressed]}><Text style={owned ? styles.buyDisabledText : styles.buyText}>{owned ? (equipped ? "已裝備" : "已擁有") : "兌換"}</Text></Pressable></View><Pressable onPress={() => setPreviewItem(item)} style={({ pressed }) => [styles.equipButton, equipped && styles.equipActive, pressed && styles.pressed]}><Text style={[styles.equipText, equipped && styles.equipTextActive]}>{equipped ? "查看外觀" : "試穿"}</Text></Pressable></JianghuPaperPanel>; })}</View></> : null}
  </ScrollView><ShopTryOnModal item={previewItem} onClose={() => setPreviewItem(null)} /></View></ScreenContainer>;
}

function ShopTryOnModal({ item, onClose }: { item: AvatarItem | null; onClose: () => void }) {
  const game = useGame();
  if (!item) return null;
  const owned = game.userItems.some((entry) => entry.item_id === item.id && entry.owned);
  const equipped = game.avatarEquipment[item.type] === item.id;
  const previewEquipment = { ...game.avatarEquipment, [item.type]: item.id };
  const buy = () => { if (game.buyAvatarItem(item.id)) return; Alert.alert("江湖幣不足", "完成更多修煉，再回來換取這件外觀吧。 "); };
  return <Modal visible transparent animationType="fade" onRequestClose={onClose}><View style={styles.tryOnBackdrop}><JianghuPaperPanel style={styles.tryOnCard}><Pressable onPress={onClose} style={styles.tryOnClose}><Text style={styles.tryOnCloseText}>×</Text></Pressable><Text style={styles.tryOnKicker}>試穿預覽 · {avatarSlotLabel[item.type]}</Text><Text style={styles.tryOnTitle}>{item.name}</Text><View style={styles.tryOnAvatarFrame}><CharacterAvatar equipment={previewEquipment} height={248} accessibilityLabel={`試穿 ${item.name} 的角色模型`} /></View><Text style={[styles.tryOnRarity, { color: avatarRarityColor[item.rarity] }]}>{avatarRarityLabel[item.rarity]} · {item.description}</Text><View style={styles.tryOnActions}>{owned ? <Pressable onPress={() => { game.equipAvatarItem(item.id); onClose(); }} style={({ pressed }) => [styles.tryOnEquip, equipped && styles.equipActive, pressed && styles.pressed]}><Text style={styles.tryOnEquipText}>{equipped ? "已裝備" : "裝備這件外觀"}</Text></Pressable> : <Pressable onPress={buy} style={({ pressed }) => [styles.tryOnBuy, pressed && styles.pressed]}><Text style={styles.tryOnBuyText}>◈ {item.price_coin}　兌換入行囊</Text></Pressable>}</View></JianghuPaperPanel></View></Modal>;
}

const styles = StyleSheet.create({
  page: { flex: 1, position: "relative" }, scroll: { zIndex: 1 }, content: { paddingTop: 12, paddingBottom: 34 },
  balance: { position: "absolute", right: 12, top: 12, borderRadius: 13, paddingHorizontal: 10, paddingVertical: 6, backgroundColor: "rgba(255,244,211,0.92)", alignItems: "flex-end" }, balanceLabel: { color: "#86673B", fontSize: 9, lineHeight: 12, fontWeight: "800" }, balanceValue: { color: "#9A661B", fontSize: 12, lineHeight: 16, fontWeight: "900", marginTop: 1 },
  sectionHead: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", marginTop: 18, marginBottom: 10 }, kicker: { color: "#A66B2E", fontSize: 10, lineHeight: 14, letterSpacing: 1, fontWeight: "900" }, heading: { color: jianghuColors.ink, fontSize: 20, lineHeight: 26, fontWeight: "900", marginTop: 2 }, hint: { color: jianghuColors.muted, fontSize: 11, lineHeight: 15, fontWeight: "800" },
  tabs: { flexDirection: "row", padding: 5, borderRadius: 18, marginBottom: 13 }, tab: { flex: 1, alignItems: "center", paddingVertical: 9, borderRadius: 13 }, tabActive: { backgroundColor: jianghuColors.indigo }, tabText: { color: "#6F837B", fontSize: 12, lineHeight: 16, fontWeight: "800" }, tabTextActive: { color: "#FFF5D8", fontWeight: "900" },
  grid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", gap: 10 }, product: { width: "48.4%", padding: 11, minHeight: 238, borderWidth: 1 }, productTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, rarityMedallion: { width: 58, height: 58, borderRadius: 18, backgroundColor: "#F2EFE5", borderWidth: 1, alignItems: "center", justifyContent: "center", overflow: "hidden" }, itemImage: { width: 52, height: 52 }, itemGlyph: { fontSize: 25, lineHeight: 30, fontWeight: "900" }, rarity: { fontSize: 10, lineHeight: 13, fontWeight: "900", marginTop: 4 }, productName: { color: jianghuColors.ink, fontSize: 13, lineHeight: 18, fontWeight: "900", marginTop: 10 }, productDesc: { color: "#74847E", fontSize: 10, lineHeight: 14, marginTop: 4, minHeight: 28 }, productMeta: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 7 }, productType: { color: "#55756E", fontSize: 9, lineHeight: 12, fontWeight: "800" }, levelRule: { color: "#9B8562", fontSize: 9, lineHeight: 12, fontWeight: "900" }, priceRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 4, marginTop: 9 }, price: { color: jianghuColors.gold, fontSize: 11, lineHeight: 14, fontWeight: "900" }, buyButton: { borderRadius: 10, backgroundColor: jianghuColors.cinnabar, borderWidth: 1, borderColor: "#A83B32", paddingHorizontal: 8, paddingVertical: 7 }, buyText: { color: "#FFFFFF", fontSize: 10, lineHeight: 13, fontWeight: "900" }, buyDisabled: { backgroundColor: "#E9E5D9", borderColor: "#D3CCBC" }, buyDisabledText: { color: "#87928A", fontSize: 9, lineHeight: 13, fontWeight: "800" }, equipButton: { alignSelf: "stretch", alignItems: "center", borderRadius: 10, paddingVertical: 7, marginTop: 7, borderWidth: 1, borderColor: "#9CB7AE", backgroundColor: "#F4F1E7" }, equipActive: { backgroundColor: "#315F78", borderColor: "#315F78" }, equipText: { color: jianghuColors.jade, fontSize: 10, lineHeight: 13, fontWeight: "900" }, equipTextActive: { color: "#FFF5D8" }, productFoot: { color: "#89958B", fontSize: 9, lineHeight: 13, marginTop: 10 }, pressed: { opacity: 0.8, transform: [{ scale: 0.98 }] },
  avatarSectionHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "baseline", marginTop: 20, marginBottom: 10 }, avatarSectionTitle: { color: jianghuColors.ink, fontSize: 17, lineHeight: 22, fontWeight: "900" }, avatarSectionHint: { color: "#819189", fontSize: 10, lineHeight: 14, fontWeight: "800" }, tryOnBackdrop: { flex: 1, backgroundColor: "rgba(20,52,51,0.58)", justifyContent: "center", alignItems: "center", padding: 20 }, tryOnCard: { width: "100%", padding: 19, alignItems: "center" }, tryOnClose: { position: "absolute", right: 12, top: 12, width: 30, height: 30, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: "#E8EFE8", zIndex: 2 }, tryOnCloseText: { color: "#315F78", fontSize: 21, lineHeight: 25, fontWeight: "900" }, tryOnKicker: { color: "#A66B2E", fontSize: 10, lineHeight: 14, fontWeight: "900", letterSpacing: 0.8 }, tryOnTitle: { color: jianghuColors.ink, fontSize: 20, lineHeight: 26, fontWeight: "900", marginTop: 3 }, tryOnAvatarFrame: { width: "100%", height: 234, borderRadius: 18, alignItems: "center", justifyContent: "center", marginTop: 12, overflow: "hidden", backgroundColor: "#DDEDE6", borderWidth: 1, borderColor: "#BED8CC" }, tryOnRarity: { alignSelf: "stretch", fontSize: 11, lineHeight: 16, fontWeight: "800", marginTop: 11, textAlign: "center" }, tryOnActions: { width: "100%", marginTop: 13 }, tryOnEquip: { minHeight: 47, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: jianghuColors.cinnabar, borderWidth: 1, borderColor: "#A83B32" }, tryOnEquipText: { color: "#FFFFFF", fontSize: 12, lineHeight: 16, fontWeight: "900" }, tryOnBuy: { minHeight: 47, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#315F78", borderWidth: 1, borderColor: "#204C60" }, tryOnBuyText: { color: "#FFF5D8", fontSize: 12, lineHeight: 16, fontWeight: "900" },
});
